# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fe1789b6513e5925d1f71e37847e81b0fe17fb36f3c115a9166e115d423201bb4af76593289dff98c43dfdfdc643c4d7697de33fbf1d837e4e53dc9f58780ae

test:
  secret_key_base: 5aa51c2b9c83a2fc116d7a5680af16b1174c7eba0eb11d017e9e53016e6d6b6c4828e6b108cf9292ca18cdee2db45b8d82720696d1d80fb5770c1db5df33affe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
